# Generated by Django 2.1.4 on 2019-01-04 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pseudo', models.CharField(max_length=30)),
                ('access', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
